[package]
name = "edgedb-protocol"
license = "MIT/Apache-2.0"
version = "0.3.0"
authors = ["MagicStack Inc. <hello@magic.io>"]
edition = "2018"
description = """
    Low-level protocol implemenentation for EdgeDB database client.
    Use edgedb-client for applications instead.
"""

[dependencies]
bytes = "1.0.1"
snafu = {version="0.7.0"}
uuid = "1.1.2"
num-bigint = {version="0.4.3", optional=true}
num-traits = {version="0.2.10", optional=true}
bigdecimal = {version="0.3.0", optional=true}
chrono = {version="0.4.10", optional=true}
edgedb-errors = {path = "../edgedb-errors", version="0.2.0"}
bitflags = "1.3.2"

[features]
default = []
with-num-bigint = ["num-bigint", "num-traits"]
with-bigdecimal = ["bigdecimal", "num-bigint", "num-traits"]
with-chrono = ["chrono"]
all-types = ["with-num-bigint", "with-bigdecimal", "with-chrono"]

[dev-dependencies]
rand = "0.8"
pretty_assertions = "1.2.1"

[lib]
