// a macro should always fully qualify names it uses, so it works even if the relevant item hasn't been imported, or a conflicting item has been imported
// this test ensures that the code generated by the derive Queryable macro does not reference names from the prelude
#![no_implicit_prelude]

#[derive(::gel_derive::Queryable)]
#[allow(dead_code)]
struct Test {
    field: i64,
}
