on:
  push:
    tags:
    - releases/edgedb-errors/v*

name: Release edgedb-errors

jobs:
  test_and_publish:
    name: Test and publish
    runs-on: ubuntu-latest
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build the nix shell
        run: nix develop --command just --version
      - uses: Swatinem/rust-cache@v2

      # test
      - name: Test
        run: nix develop --command cargo test --all-features --package=edgedb-errors

      # verify that git tag matches cargo version
      - run: |
          set -x
          cargo_version="$(cargo metadata --format-version 1 \
            | jq -r '.packages[] | select(.name=="edgedb-errors") | .version')"
          tag_version="${GITHUB_REF#refs/tags/releases/edgedb-errors/v}"
          test "$cargo_version" = "$tag_version"

      - working-directory: ./edgedb-errors
        run: |
          nix develop --command cargo publish --token=${{ secrets.CARGO_REGISTRY_TOKEN }}
